#!/usr/bin/env python3
"""Snapshot the Promise Ledgers into claims/ledger-snapshot.json.

The ledgers live in the private AlterYield/Atteste repo, which neither the
Netlify build image nor this repo's CI can read. So the claim gate reads a
committed snapshot, and this script refreshes it.

Source, in order of preference:
  1. --repo PATH (or ATTESTE_REPO): `git show origin/main:contracts/<file>`
     after a fetch. Always origin/main: a local checkout of Atteste has been
     weeks stale before, and a stale read nearly re-escalated a made decision
     (2026-10-08).
  2. --contracts DIR (or ATTESTE_CONTRACTS): plain files, for CI with a token.

    python3 scripts/claims/sync_ledger.py --repo ~/Projects/atteste
    python3 scripts/claims/sync_ledger.py --check   # exit 1 if the snapshot would change

Only ids and statuses are copied: this repo is public and the ledger is not,
so promise text and risks stay in AlterYield/Atteste.

When Charl moves an entry to shipping, re-run this and commit the result: the
blocks gated on that id appear on atteste.art with no copy change.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "claims" / "ledger-snapshot.json"
FILES = {
    "gallery-promises.yaml": "promises",
    "artist-promises.yaml": "promises",
    "app-features.yaml": "features",
}


def read_from_repo(repo: Path) -> tuple[dict[str, str], str]:
    subprocess.run(["git", "-C", str(repo), "fetch", "-q", "origin", "main"], check=True)
    sha = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "origin/main"], check=True, capture_output=True, text=True
    ).stdout.strip()
    texts = {}
    for name in FILES:
        texts[name] = subprocess.run(
            ["git", "-C", str(repo), "show", f"origin/main:contracts/{name}"],
            check=True, capture_output=True, text=True,
        ).stdout
    return texts, sha


def read_from_dir(d: Path) -> tuple[dict[str, str], str]:
    return {name: (d / name).read_text(encoding="utf-8") for name in FILES}, os.environ.get("ATTESTE_SHA", "unknown")


def build(texts: dict[str, str], sha: str) -> dict:
    entries: dict[str, dict] = {}
    for name, key in FILES.items():
        doc = yaml.safe_load(texts[name]) or {}
        for e in doc.get(key) or []:
            if not isinstance(e, dict) or "id" not in e:
                continue
            if e["id"] in entries:
                sys.exit(f"FATAL: duplicate ledger id {e['id']} ({name})")
            row = {
                "status": e.get("status"),
                "ledger": name,
                "last_verified": str(e.get("last_verified") or ""),
            }
            if e.get("superseded_by"):
                row["superseded_by"] = e["superseded_by"]
            entries[e["id"]] = row
    return {
        "_comment": "Generated by scripts/claims/sync_ledger.py from AlterYield/Atteste contracts/. Do not edit by hand.",
        "source": "AlterYield/Atteste@origin/main",
        "source_sha": sha,
        "entries": dict(sorted(entries.items())),
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.environ.get("ATTESTE_REPO"))
    ap.add_argument("--contracts", default=os.environ.get("ATTESTE_CONTRACTS"))
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed snapshot is out of date")
    args = ap.parse_args()

    if args.repo:
        texts, sha = read_from_repo(Path(args.repo).expanduser())
    elif args.contracts:
        texts, sha = read_from_dir(Path(args.contracts).expanduser())
    else:
        default = Path.home() / "Projects" / "atteste"
        if not default.exists():
            sys.exit("FATAL: pass --repo or --contracts (or set ATTESTE_REPO / ATTESTE_CONTRACTS)")
        texts, sha = read_from_repo(default)

    snap = build(texts, sha)
    old = json.loads(OUT.read_text()) if OUT.exists() else {}
    same = old.get("entries") == snap["entries"]
    if args.check:
        if same:
            print(f"snapshot current ({len(snap['entries'])} entries)")
            return
        changed = sorted(
            k for k in set(old.get("entries", {})) | set(snap["entries"])
            if old.get("entries", {}).get(k, {}).get("status") != snap["entries"].get(k, {}).get("status")
        )
        sys.exit(f"snapshot stale: status changed for {changed or '(metadata only)'}")

    snap["synced_at"] = old.get("synced_at") if same else datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(snap, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    by: dict[str, int] = {}
    for e in snap["entries"].values():
        by[e["status"]] = by.get(e["status"], 0) + 1
    print(f"wrote {OUT.relative_to(ROOT)}  {len(snap['entries'])} entries  {by}  @ {sha[:8]}")


if __name__ == "__main__":
    main()
